# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('control', models.CharField(max_length=180)),
                ('test_group_1', models.CharField(max_length=180)),
                ('test_group_2', models.CharField(max_length=180)),
                ('test_group_3', models.CharField(max_length=180)),
                ('test_group_4', models.CharField(max_length=180)),
                ('test_group_5', models.CharField(max_length=180)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
