# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='control',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.CharField(default='No Name Specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_1',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_2',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_3',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_4',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_5',
            field=models.CharField(max_length=240),
        ),
    ]
