# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0003_auto_20161112_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.CharField(default='No Name Specified', max_length=20),
            preserve_default=False,
        ),
    ]
