# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0004_auto_20161112_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='test_group_order',
            field=models.CharField(default='In Order', max_length=240),
            preserve_default=False,
        ),
    ]
