# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0005_trial_test_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='control_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='discard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_1_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_2_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_3_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_4_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_5_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
