# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0006_auto_20161204_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='control_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_1_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_2_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_3_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_4_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='test_group_5_errors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='control_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_1_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_2_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_3_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_4_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='test_group_5_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
