# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_data', '0007_auto_20161204_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_1',
            new_name='stage_1',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_1_errors',
            new_name='stage_1_errors',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_1_time',
            new_name='stage_1_time',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_2',
            new_name='stage_2',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_2_errors',
            new_name='stage_2_errors',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_2_time',
            new_name='stage_2_time',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_3',
            new_name='stage_3',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_3_errors',
            new_name='stage_3_errors',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_3_time',
            new_name='stage_3_time',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_4',
            new_name='stage_4',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_4_errors',
            new_name='stage_4_errors',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_4_time',
            new_name='stage_4_time',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_5',
            new_name='stage_5',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_5_errors',
            new_name='stage_5_errors',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_5_time',
            new_name='stage_5_time',
        ),
        migrations.RenameField(
            model_name='trial',
            old_name='test_group_order',
            new_name='stage_order',
        ),
    ]
